image:
  server:
    repository: warpcomdev/wso2si-server
    tag: latest
    pullPolicy: Always
  integrator:
    repository: warpcomdev/wso2si-integrator
    tag: latest
    pullPolicy: IfNotPresent
  processor:
    repository: warpcomdev/wso2si-processor
    tag: latest
    pullPolicy: IfNotPresent

resources:
  server:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 4Gi
      cpu: "2"
  integrator:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 4Gi
      cpu: "2"
  processor:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 4Gi
      cpu: "2"

replication:
  initialCount: 1

proxy:
  enabled: true
  image: nginx
  # alpine for bcrypt support in htpasswd
  tag: 1.19.2-alpine
  resources:
    requests:
      cpu: "100m"
      memory: "64M"
    limits:
      cpu: "250m"
      memory: "128M"
